<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\PaymentServicesPaypal\Block\Customer\Vault\AddCardForm;

/** @var AddCardForm|Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div id="paymentservices_add_vault_card">
    <?= $block->getChildHtml('paypal_cardfields_form') ?>

    <div><?= $block->getChildHtml('address_form') ?></div>

    <button type="button" id="paymentservices-add-card-button" role="add-card" title="<?= $escaper->escapeHtmlAttr(__('Save New Card')) ?>" class="mt-8 inline-flex items-center justify-center gap-2 rounded-md text-sm font-semibold border px-4 py-2 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-600 disabled:opacity-50 disabled:pointer-events-none bg-blue-600 text-white border-blue-600 hover:bg-blue-700 add">
        <span><?= $escaper->escapeHtml(__('Save New Card')) ?></span>
    </button>
</div>
