<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Review\Block\Rating\Entity\Detailed $block */
?>
<p class="no-rating text-sm text-neutral-700">
    <a href="#review-form" class="font-medium text-blue-600 hover:text-blue-800 hover:underline">
        <?= $block->escapeHtml(__('Be the first to review this product')) ?>
    </a>
</p>
