<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()) : ?>
    <a href="#"
       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
       class="inline-flex items-center justify-center gap-2 rounded-md text-sm font-semibold border border-neutral-300 px-4 py-2 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-600 disabled:opacity-50 disabled:pointer-events-none use-ajax towishlist action-towishlist">
        <span><?= $block->escapeHtml(__('Move to Wishlist')) ?></span>
    </a>
<?php endif ?>
