<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Wishlist\Block\Rss\EmailLink $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var \Magento\Wishlist\Helper\Data $wishlistHelper */
$wishlistHelper = $block->getData('wishlistHelper');
?>
<?php if ($block->getLink()): ?>
<p id="wishlist-rss-email-link">
    <?= $block->escapeHtml(__("RSS link to %1's wishlist", $wishlistHelper->getCustomerName())) ?>
    <br />
    <a href="<?= $block->escapeUrl($block->getLink()) ?>" class="break-all text-blue-600 hover:underline"><?= $block->escapeUrl($block->getLink()) ?></a>
</p>
    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
        "font-size:12px; line-height:16px; margin:0 0 16px;",
        'p#wishlist-rss-email-link'
    ) ?>
<?php endif; ?>
