<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Payment\Info $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div id="payment_form_<?= $block->escapeHtmlAttr($block->getMethodCode()) ?>" class="m-0 hss list-none p-0 text-sm text-neutral-700">
    <?= $block->escapeHtml(__(
        'You will be required to enter your payment details after you place an order.'
    )); ?>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    'div#payment_form_' . $block->escapeHtml($block->getMethodCode())
) ?>
