<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$target = $block->getTarget();
$label = $block->getLabel();
?>
<a class="action skip <?= $block->escapeHtmlAttr($target) ?><?= $target === 'gallery-next-area' ? ' sr-only' : '' ?>"
   href="#<?= $block->escapeHtmlAttr($target) ?>">
    <span>
        <?= $block->escapeHtml($label) ?>
    </span>
</a>
