<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */


/**
 * @var \Magento\Paypal\Block\Checkout\Onepage\Success\BillingAgreement $block
 */
?>
<p class="text-sm text-neutral-700"
   data-mage-init='{"Magento_Paypal/js/in-context/billing-agreement": {"invalidateOnLoad" : true}}'>
    <?= $block->escapeHtml(__('Your billing agreement # is: ')) ?>
    <a href="<?= $block->escapeUrl($block->getAgreementUrl()) ?>"
       class="font-medium text-blue-700 underline-offset-2 hover:underline">
        <?= $block->escapeHtml($block->getAgreementRefId()) ?>
    </a>.
</p>
