<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\OfflinePayments\Block\Info\Checkmo
 */
?>
<dl class="payment-method checkmemo space-y-2 text-sm text-neutral-800">
    <dt class="text-base font-semibold text-neutral-900"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getInfo()->getAdditionalInformation()) : ?>
        <?php if ($block->getPayableTo()) : ?>
            <dd class="content text-neutral-700">
                <strong class="font-medium text-neutral-900"><?= $block->escapeHtml(__('Make Check payable to')) ?></strong>
                <?= $block->escapeHtml($block->getPayableTo()) ?>
            </dd>
        <?php endif; ?>
        <?php if ($block->getMailingAddress()) : ?>
            <dd class="content text-neutral-700">
                <strong class="font-medium text-neutral-900"><?= $block->escapeHtml(__('Send Check to')) ?></strong>
                <address class="checkmo mailing address not-italic">
                    <?= /* @noEscape */ nl2br($block->escapeHtml($block->getMailingAddress())) ?>
                </address>
            </dd>
        <?php endif; ?>
    <?php endif; ?>
</dl>
