<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Cms\Block\Widget\Page\Link $block
 */
?>
<span class="widget inline-block">
    <a class="font-medium text-blue-600 hover:text-blue-800 hover:underline" <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <span><?= $block->escapeHtml($block->getLabel()) ?></span>
    </a>
</span>
