<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
// phpcs:disable Magento2.PHP.ShortEchoSyntax.ShortEchoTag

/** @var $block \Magento\Ui\Block\Wrapper */
?>

<?php /* @noEscape */ echo $block->renderApp(
    [
        'widget_columns' => [
            'displayMode' => 'grid'
        ],
        'image' => [
            'imageCode' => 'category_page_grid'
        ]
    ]
);
