<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Wishlist\Block\AddToWishlist $block */
$jsonHelper = $this->helper(\Magento\Framework\Json\Helper\Data::class);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $jsonHelper->jsonEncode($block->getWishlistOptions()) ?>
        }
    }
</script>
