<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Sales\Block\Order\Email\Creditmemo\Items $block */
/** @var \Magento\Framework\Escaper $escaper */

?>
<?php $_creditmemo = $block->getCreditmemo() ?>
<?php $_order      = $block->getOrder() ?>
<?php if ($_creditmemo && $_order) : ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info" scope="col">
                    <?= $escaper->escapeHtml(__('Items')) ?>
                </th>
                <th class="item-qty" scope="col">
                    <?= $escaper->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-subtotal" scope="col">
                    <?= $escaper->escapeHtml(__('Subtotal')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_creditmemo->getAllItems() as $_item) : ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('creditmemo_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
