<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Sales\Block\Order\Info $block */
?>
<span class="order-status inline-flex items-center rounded-md border border-neutral-200 bg-neutral-50 px-2.5 py-0.5 text-sm font-medium text-neutral-800"><?= $block->escapeHtml($block->getOrder()->getStatusLabel()) ?></span>
