<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Sales\Block\Order\Info $block */
?>
<div class="order-date text-sm text-neutral-800">
    <span class="block text-sm font-medium text-neutral-800 mb-1"><?= $block->escapeHtml(__('Order Date:')) ?></span>
    <span class="tabular-nums text-neutral-700"><?= $block->escapeHtml(
        $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG)
    ) ?></span>
</div>
