<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer $block */
$_item = $block->getItem();
?>
<span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
    <span class="cart-price">
        <?= /* @noEscape */ $block->getOrder()->formatPrice($block->getItem()->getPrice()) ?>
    </span>
</span>
