<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\PaymentServicesPaypal\Block\Customer\Vault\AddCardButton;

/** @var \Magento\Framework\Escaper $escaper */
/** @var AddCardButton $block */
/** @var SecureHtmlRenderer $secureRenderer */
?>

<?php if ($block->isButtonEnabled()): ?>
    <button type="button" role="add-card" title="<?= $escaper->escapeHtmlAttr(__('Add New Card')) ?>" class="add add-card-btn mt-8 inline-flex items-center justify-center gap-2 rounded-md border border-blue-600 bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-600 disabled:pointer-events-none disabled:opacity-50">
        <span><?= $escaper->escapeHtml(__('Add New Card')) ?></span>
    </button>

    <script type="text/x-magento-init">
        {
            ".add-card-btn": {
                "Magento_PaymentServicesPaypal/js/view/customer_account/vault/add-card-button": {
                    "addCard": "button[role='add-card']",
                    "addCardLocation": "<?= $escaper->escapeJs($block->getAddCardUrl()) ?>"
                }
            }
        }
    </script>
<?php endif ?>
