<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Paypal\Block\Express\Shortcut $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->getIsInCatalogProduct()) : ?>
    <input type="hidden" id="pp-checkout-url" name="return_url" value="<?= $escaper->escapeHtmlAttr('') ?>" class="hidden"/>
<?php endif; ?>
