<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\ReCaptchaUi\Block\ReCaptcha $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div
    class="field-recaptcha mb-4 min-h-0"
    id="<?= $escaper->escapeHtmlAttr($block->getRecaptchaId() . '-container') ?>"
    data-bind="scope:'<?= $escaper->escapeHtmlAttr($block->getRecaptchaId()) ?>'"
>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#<?= $escaper->escapeJs($block->getRecaptchaId() . '-container') ?>": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    }
}
</script>
