<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->getSearchTermsLog()->isPageCacheable()) : ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_CatalogSearch/js/search-terms-log": {
                "url": "<?= $escaper->escapeJs($block->getUrl('catalogsearch/searchTermsLog/save')) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
