<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\PageBuilder\Block\WidgetInitializer $block */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_PageBuilder/js/widget-initializer": {
                "config": <?= /* @noEscape */ $block->getConfig(); ?>,
                "breakpoints": <?= /* @noEscape */ $block->getBreakpoints(); ?>
            }
        }
    }
</script>
