<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

?>
<div class="flex flex-wrap gap-2">
    <?php $_order = $block->getOrder() ?>
    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?=
        /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="inline-flex items-center justify-center gap-2 rounded-md text-sm font-semibold border border-neutral-300 px-4 py-2 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-600 disabled:opacity-50 disabled:pointer-events-none text-neutral-800 hover:bg-neutral-50 order">
            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
        </a>
    <?php endif ?>
    <a href="<?= $block->escapeUrl($block->getPrintUrl($_order)) ?>"
       class="inline-flex items-center justify-center gap-2 rounded-md text-sm font-semibold border border-neutral-300 px-4 py-2 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-600 disabled:opacity-50 disabled:pointer-events-none text-neutral-800 hover:bg-neutral-50 print"
       target="_blank"
       rel="noopener noreferrer">
        <span><?= $block->escapeHtml(__('Print Order')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
