<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Actions $block */
?>
<?php $children = $block->getChildNames(); ?>
<?php if ($children) : ?>
    <div class="<?= $block->escapeHtmlAttr($block->getCssClass()) ?> flex flex-wrap items-center gap-2">
        <?php foreach ($children as $childName) : ?>
            <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
        <?php endforeach;?>
    </div>
<?php endif; ?>
