<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Comment $block  */

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
?>

<div class="mb-4 comment-box">
    <label class="block text-sm font-medium text-neutral-800 mb-1" for="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>">
        <span><?= $block->escapeHtml(__('Comment')) ?></span>
    </label>
    <div class="mt-1">
        <textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>"
                  placeholder="<?= /* @noEscape */ $this->helper(\Magento\Wishlist\Helper\Data::class)->defaultCommentString() ?>"
                  name="description[<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>]"
                  title="<?= $block->escapeHtmlAttr(__('Comment')) ?>"
                  class="product-item-comment w-full rounded-md border border-neutral-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                  <?= $item->getProduct()->isSaleable() ? '' : 'disabled="disabled"' ?>><?= ($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
