<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="text-base font-semibold leading-snug text-neutral-900">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="text-blue-600 hover:text-blue-800 hover:underline">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
