<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Downloadable product type
 *
 * @var $block \Magento\Downloadable\Block\Catalog\Product\View\Type
 */
?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <div class="stock available text-sm font-medium text-green-700"
             title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else : ?>
        <div class="stock unavailable text-sm font-medium text-red-700"
             title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml() ?>
