<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<form action="<?= $block->escapeUrl($block->getUrl('productalert/unsubscribe/stock')) ?>"
      method="post"
      data-form="unsubscription_form">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" id="productId" name="product" value="<?= $block->escapeHtmlAttr($block->getProductId()) ?>" />
</form>
<script type="text/x-magento-init">
    {
        "[data-form=unsubscription_form]": {
            "Magento_ProductAlert/js/form-submitter": {}
        }
    }
</script>
