<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/**
 * @var \Magento\Weee\Block\Item\Price\Renderer $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Weee\Helper\Data $weeeHelper */
$weeeHelper = $block->getData('weeeHelper');

$item = $block->getItem();
?>
<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()): ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtmlAttr(__('Incl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total text-sm tabular-nums text-neutral-900"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int) $item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price text-sm tabular-nums text-neutral-900">
        <?php endif; ?>
            <?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceInclTax()) ?>
            </span>

        <?php if ($weeeHelper->getApplied($item)): ?>
            <span class="hidden cart-tax-info" id="unit-item-tax-details<?= (int) $item->getId() ?>">
                <?php foreach ($weeeHelper->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */ $block->formatPrice($tax['amount_incl_tax'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </span>

            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total text-sm tabular-nums text-neutral-900"
                    data-mage-init='{"taxToggle": {"itemTaxId" : "#unit-item-tax-details<?= (int) $item->getId() ?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total Incl. Tax')) ?>">
                        <?= /* @noEscape */ $block->formatPrice($block->getFinalUnitDisplayPriceInclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>

<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()): ?>
    <span class="price-excluding-tax" data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>">
        <?php if ($block->displayPriceWithWeeeDetails()): ?>
            <span class="cart-tax-total text-sm tabular-nums text-neutral-900"
                data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?= (int) $item->getId() ?>"}}'>
        <?php else: ?>
            <span class="cart-price text-sm tabular-nums text-neutral-900">
        <?php endif; ?>
                <?= /* @noEscape */ $block->formatPrice($block->getUnitDisplayPriceExclTax()) ?>
            </span>

        <?php if ($weeeHelper->getApplied($item)): ?>
            <span class="hidden cart-tax-info" id="eunit-item-tax-details<?= (int) $item->getId() ?>">
                <?php foreach ($weeeHelper->getApplied($item) as $tax): ?>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr($tax['title']) ?>">
                        <?= /* @noEscape */ $block->formatPrice($tax['amount'], true, true) ?>
                    </span>
                <?php endforeach; ?>
            </span>
            <?php if ($block->displayFinalPrice()): ?>
                <span class="cart-tax-total text-sm tabular-nums text-neutral-900"
                      data-mage-init='{"taxToggle": {"itemTaxId" : "#eunit-item-tax-details<?=(int)$item->getId()?>"}}'>
                    <span class="weee" data-label="<?= $block->escapeHtmlAttr(__('Total')) ?>">
                        <?= /* @noEscape */ $block->formatPrice($block->getFinalUnitDisplayPriceExclTax()) ?>
                    </span>
                </span>
            <?php endif; ?>
        <?php endif; ?>
    </span>
<?php endif; ?>
