<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

/** @var \Magento\Persistent\Block\Header\Additional $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<script type="application/javascript">
    window.persistent = <?=/* @noEscape */ $block->getConfig()?>;
    window.notYouLink = '<?= $escaper->escapeJs($block->getLinkAttributes()) ?>';
</script>
<script type="text/x-magento-init">
    {
        "li.greet.welcome > span.not-logged-in": {
            "Magento_Persistent/js/view/additional-welcome": {}
        }
    }
</script>
