<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\GoogleGtag\ViewModel\Adwords $adsViewModel */

$adsViewModel = $block->getViewModel();
?>

<?php if ($adsViewModel->isGoogleAdwordsConfigurable() && $adsViewModel->isGoogleAdwordsActive()): ?>
    <?php $conversionId = $adsViewModel->getConversionId(); ?>
    <?php $conversionLabel = $adsViewModel->getConversionLabel(); ?>
    <?php $gtagSiteSrc = $adsViewModel->getConversionGtagGlobalSiteTagSrc(); ?>
    <!-- BEGIN GOOGLE ADWORDS CODE -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_GoogleGtag/js/google-adwords": {
                "conversionId": "<?= $escaper->escapeHtml($conversionId) ?>",
                "gtagSiteSrc": "<?= $escaper->escapeHtml($gtagSiteSrc) ?>",
                "conversionLabel": "<?= $escaper->escapeHtml($conversionLabel) ?>"
            }
        }
    }
    </script>
    <!-- END GOOGLE ADWORDS CODE -->
<?php endif; ?>
