<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Payment\Block\Transparent\Form $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$methodCode = $block->getMethodCode();
$code = $block->escapeHtmlAttr($methodCode);
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
$ccType = $block->getInfoData('cc_type');
$content = '<img src=\"' . $block->escapeUrl($block->getViewFileUrl('Magento_Checkout::cvv.png')) . '\" alt=\"' .
    $block->escapeHtml(__('Card Verification Number Visual Reference')) . '\" title=\"' .
    $block->escapeHtml(__('Card Verification Number Visual Reference')) . '\" />';
?>

<!-- IFRAME for request to Payment Gateway -->
<iframe width="0" height="0" id="<?= /* @noEscape */ $code ?>-transparent-iframe"
        data-container="<?= /* @noEscape */ $code ?>-transparent-iframe" allowtransparency="true"
        frameborder="0"  name="iframeTransparent"
        src="<?= $block->escapeUrl($block->getViewFileUrl('blank.html')) ?>"></iframe>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display: none; width: 100%; background-color: transparent;",
    'iframe#' . /* @noEscape */ $code . '-transparent-iframe'
) ?>
<form class="form" id="co-transparent-form" action="#" method="post" data-mage-init='{
    "transparent":{
        "controller":"<?= $block->escapeJs($block->getRequest()->getControllerName()) ?>",
        "gateway":"<?= $block->escapeJs($methodCode) ?>",
        "orderSaveUrl":"<?= $block->escapeJs($block->getOrderUrl()) ?>",
        "cgiUrl":"<?= $block->escapeJs($block->getCgiUrl()) ?>",
        "dateDelim":"<?= $block->escapeJs($block->getDateDelim()) ?>",
        "cardFieldsMap":<?= /* @noEscape */ $block->getCardFieldsMap() ?>,
        "nativeAction":"<?= $block->escapeJs(
            $block->getUrl('checkout/onepage/saveOrder', ['_secure' => $block->getRequest()->isSecure()])
        ) ?>"
    }, "validation":[]}'>
    <fieldset class="fieldset ccard <?= /* @noEscape */ $code ?>" id="payment_form_<?= /* @noEscape */ $code ?>">
        <legend class="mb-3 text-base font-semibold text-neutral-900">
            <span><?= $block->escapeHtml(__('Credit Card Information')) ?></span>
        </legend>
        <div class="mb-4 required type">
            <label for="<?= /* @noEscape */ $code ?>_cc_type" class="block text-sm font-medium text-neutral-800 mb-1">
                <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
            </label>
            <div class="mt-1">
                <select id="<?= /* @noEscape */ $code ?>_cc_type" data-container="<?= /* @noEscape */ $code ?>-cc-type"
                        name="payment[cc_type]"
                        data-validate='{
                            required:true,
                            "validate-cc-type-select":"#<?= /* @noEscape */ $code ?>_cc_number"
                        }'>
                    <option value=""><?= $block->escapeHtml(__('--Please Select--')) ?></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $block->escapeHtmlAttr($typeCode) ?>"
                        <?php if ($typeCode == $ccType): ?> selected="selected"<?php endif; ?>>
                        <?= $block->escapeHtml($typeName) ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="mb-4 required number">
            <label for="<?= /* @noEscape */ $code ?>_cc_number" class="block text-sm font-medium text-neutral-800 mb-1">
                <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
            </label>
            <div class="mt-1">
                <input id="<?= /* @noEscape */ $code ?>_cc_number"
                       type="number"
                       data-container="<?= /* @noEscape */ $code ?>-cc-number" name="payment[cc_number]"
                       title="<?= $block->escapeHtmlAttr(__('Credit Card Number')) ?>"
                       class="w-full rounded-md border border-neutral-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
                       value=""
                       data-validate='{
                           "required-number":true,
                           "validate-cc-number":"#<?= /* @noEscape */ $code ?>_cc_type",
                           "validate-cc-type":"#<?= /* @noEscape */ $code ?>_cc_type"
                       }'
                       autocomplete="off"/>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'oncopy',
                    "event.preventDefault();",
                    '#' . $code . '_cc_number'
                ) ?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onpaste',
                    "event.preventDefault();",
                    '#' . $code . '_cc_number'
                ) ?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'oncut',
                    "event.preventDefault();",
                    '#' . $code . '_cc_number'
                ) ?>
            </div>
        </div>
        <div class="mb-4 required date" id="<?= /* @noEscape */ $code ?>_cc_type_exp_div">
            <label for="<?= /* @noEscape */ $code ?>_expiration" class="block text-sm font-medium text-neutral-800 mb-1">
                <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
            </label>
            <div class="mt-1">
                <div class="fields group group-2">
                    <div class="mb-4 no-label month">
                        <div class="mt-1">
                            <select id="<?= /* @noEscape */ $code ?>_expiration"
                                    name="payment[cc_exp_month]"
                                    data-container="<?= /* @noEscape */ $code ?>-cc-month"
                                    class="month"
                                    data-validate='{
                                        required:true,
                                        "validate-cc-exp":"#<?= /* @noEscape */ $code ?>_expiration_yr"
                                    }'>
                            <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                                    <?php if ($k == $ccExpMonth): ?> selected="selected"<?php endif; ?>>
                                    <?= $block->escapeHtml($v) ?>
                                </option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="mb-4 no-label year">
                        <div class="mt-1">
                            <select id="<?= /* @noEscape */ $code ?>_expiration_yr"
                                    name="payment[cc_exp_year]"
                                    class="year"
                                    data-container="<?= /* @noEscape */ $code ?>-cc-year"
                                    data-validate='{required:true}'>
                            <?php foreach ($block->getCcYears() as $k => $v): ?>
                                <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                                    <?php if ($k == $ccExpYear): ?> selected="selected"<?php endif; ?>>
                                    <?= $block->escapeHtml($v) ?>
                                </option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php if ($block->hasVerification()): ?>
        <div class="mb-4 required cvv" id="<?= /* @noEscape */ $code ?>_cc_type_cvv_div">
            <label for="<?= /* @noEscape */ $code ?>_cc_cid" class="block text-sm font-medium text-neutral-800 mb-1">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="mt-1">
                <input id="<?= /* @noEscape */ $code ?>_cc_cid"
                       name="payment[cc_cid]"
                       type="number"
                       title="<?= $block->escapeHtmlAttr(__('Card Verification Number')) ?>"
                       data-container="<?= /* @noEscape */ $code ?>-cc-cvv"
                       class="w-full rounded-md border border-neutral-300 px-3 py-2 text-sm shadow-sm focus:border-blue-500 focus:ring-1 focus:ring-blue-500 cvv"
                       value=""
                       data-validate='{
                           "required-number":true,
                           "validate-cc-cvn":"#<?= /* @noEscape */ $code ?>_cc_type"
                       }' autocomplete="off"/>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'oncopy',
                    "event.preventDefault();",
                    '#' . $code . '_cc_cid'
                ) ?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onpaste',
                    "event.preventDefault();",
                    '#' . $code . '_cc_cid'
                ) ?>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'oncut',
                    "event.preventDefault();",
                    '#' . $code . '_cc_cid'
                ) ?>
                <div class="text-xs text-neutral-500 mt-1">
                    <a href="#" id="<?= /* @noEscape */ $code ?>-cvv-what-is-this" class="inline-flex items-center justify-center gap-2 rounded-md text-sm font-semibold border px-4 py-2 transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-1 focus-visible:outline-blue-600 disabled:opacity-50 disabled:pointer-events-none cvv"
                       title="<?= $block->escapeHtml(__('What is this?')) ?>" data-mage-init='{
                           "tooltip": {"content": "<?= /* @noEscape */ $content ?>"}
                       }'>
                        <span><?= $block->escapeHtml(__('What is this?')) ?></span>
                    </a>
                </div>
            </div>
        </div>
        <?php endif; ?>
    <?= $block->getChildHtml() ?>
</fieldset>
</form>
