<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */



/**
 * @var \Magento\Paypal\Block\Payflow\Link\Iframe $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @see \Magento\Paypal\Block\Payflow\Link\Iframe
 */
?>
<html>
<head>
</head>
<body>
<form id="token_form" method="GET" action="<?= $block->escapeUrl($block->getTransactionUrl()) ?>">
    <input type="hidden" name="SECURETOKEN" value="<?= $block->escapeHtmlAttr($block->getSecureToken()) ?>"/>
    <input type="hidden" name="SECURETOKENID" value="<?= $block->escapeHtmlAttr($block->getSecureTokenId()) ?>"/>
    <input type="hidden" name="MODE" value="<?= $block->escapeHtmlAttr($block->isTestMode() ? 'TEST' : 'LIVE') ?>"/>
</form>
<?php $scriptString = <<<script
    document.getElementById('token_form').submit();
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</body>
</html>
