<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Paypal\Block\Payflow\Link\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="payflowlink m-0 list-none p-0 text-sm text-neutral-700" id="payment_form_<?= $block->escapeHtmlAttr($block->getMethodCode()) ?>">
    <?= $block->escapeHtml(__('You will be required to enter your payment details after you place an order.')) ?>
</div>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    'div#payment_form_' . $block->escapeHtml($block->getMethodCode())
) ?>
