<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
?>
<dl class="payment-method space-y-2 text-sm text-neutral-800">
    <dt class="text-base font-semibold text-neutral-900"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
<?php if ($block->getInstructions()) : ?>
    <dd class="content text-neutral-700"><?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstructions())) ?></dd>
<?php endif; ?>
</dl>
